### ISSUE TITLE
rest-api get customer not working

### ISSUE THREAD

**Issue by roshany01** [roshany01/first-repo#1]
Got following keys [YjJmNDcwNDE2NDYxZGZkZGZlNGM5NmU4ZTk4MmRmMmY2MDA2NTBmOTdmMWZkMDQ0YjA5MzAxODA0NDZlMmMyYw] 
2024-03-27 14:03:15.913 TRACE [jsse-nio-8080-exec-7]  org.zalando.logbook.Logbook              : Incoming Request: 39da40b8-5fb0-499c-869d-35e575b9a6cd Remote: 10.130.12.2 GET
https://api-gateway2.nets.eu/account-service/v1/institutions/0000/customers
HTTP/1.1 accept: application/json activityid: 057b919f-5585-4140-859c-c689b5370197 connection: Keep-Alive host: ams-account-service-ams.int.apps.paas-pci.no.local uniqueregnumber: *** user-agent: Synapse-PT-HttpComponents-NIO x-branch-id: 554488 x-forwarded-host: api-gateway2.nets.eu x-forwarded-port: 61000 x-jwt-assertion: *** x-real-ip: 10.129.12.1 x-request-id: 39da40b8-5fb0-499c-869d-35e575b9a6cd 
2024-03-27 14:03:16.250  INFO [jsse-nio-8080-exec-7]  eu.nets.integration.ams.account          : Application-ID: e12931e6-07df-4830-8d84-c6ee89177c8f 
2024-03-27 14:03:22.782 TRACE [jsse-nio-8080-exec-7]  org.zalando.logbook.Logbook              : Outgoing Request: 39da40b8-5fb0-499c-869d-35e575b9a6cd Remote: localhost POST
https://lb-freya-online-apps.bbsas.no:20302/Nets_WS_API/ws
HTTP/1.1 Accept: text/xml; charset=UTF-8 X-Request-ID: 39da40b8-5fb0-499c-869d-35e575b9a6cd  <?xml version="1.0" encoding="UTF-8" standalone="no"?><soapenv:Envelope xmlns:soapenv="
[http://schemas.xmlsoap.org/soap/envelope/">](http://schemas.xmlsoap.org/soap/envelope/%22%3E)
<soapenv:Body> <GetClientByIdentityCardV2 xmlns="
[http://www.openwaygroup.com/wsint">](http://www.openwaygroup.com/wsint%22%3E)
     <IdentityCardNumber>***</IdentityCardNumber>     <IdentityCardType xmlns:xsi="
[http://www.w3.org/2001/XMLSchema-instance"](http://www.w3.org/2001/XMLSchema-instance%22)
xsi:nil="true"/>     <UserInfo>officer="WS_0000_554488"</UserInfo>     <DebugInfoPage xmlns:xsi="
[http://www.w3.org/2001/XMLSchema-instance"](http://www.w3.org/2001/XMLSchema-instance%22)
xsi:nil="true"/>     <PageSize xmlns:xsi="
[http://www.w3.org/2001/XMLSchema-instance"](http://www.w3.org/2001/XMLSchema-instance%22)
xsi:nil="true"/>     <OutObjectPage xmlns:xsi="
[http://www.w3.org/2001/XMLSchema-instance"](http://www.w3.org/2001/XMLSchema-instance%22)
xsi:nil="true"/> </GetClientByIdentityCardV2> </soapenv:Body> </soapenv:Envelope> 
2024-03-27 14:03:32.845 ERROR [jsse-nio-8080-exec-7]  eu.nets.integration.ams.account          :  eu.nets.integration.ams.account.exception.AmsAccountException: Service Unavailable 	at eu.nets.integration.ams.account.service.AmsAccountCustomersService.getCustomerbyUniqueRegNumber(AmsAccountCustomersService.java:105) 	at eu.nets.integration.ams.account.controller.AmsAccountCustomersController.getCustomerbyUniqueRegNumber(AmsAccountCustomersController.java:66) 	at

**Comment by roshany01** [comment]
*item1*

**Comment by roshany01** [comment]
item2
